name: Build Thesis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-thesis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Needed to push image to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Thesis PDF inside Devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository_owner }}/university-of-tsukuba-sie-latex-template-container
          runCmd: make

      - name: Upload compiled PDF
        uses: actions/upload-artifact@v4
        with:
          name: thesis-pdf
          path: latex/*.pdf
